### ISSUE TITLE
Gcloud stops working

### ISSUE THREAD

**Issue by sn-o-w** [cloux/LinkSanitizer#2]
For some reason, having Link Sanitizer enabled prevents the following page from loading properly: https://console.cloud.google.com/

**Comment by cloux** [comment]
Hi, this should not be happening. The Google Console uses the ServiceLogin, which is whitelisted [here](https://github.com/cloux/LinkSanitizer/blob/346bc78a0b711d4fde08e6fc02fffa91af7a667c/linksanitizer.user.js#L29). I can login without any issues into Google Cloud, so I cannot replicate the issue. Could you please post this information:

 * enable the developer tools in your browser (Ctrl+Shift+I, or F12, or Menu -> More Tools -> Web Developer Tools)
 * select the "Console" tab
 * reload the problematic website (F5) and try to login again
 * send all lines from the console that say: "Hyperlink:", followed by "SANITIZED:"

Depending on the result I will add any whitelist rule if needed.

**Comment by sn-o-w** [comment]
IIRC, the page had become unresponsive and got stuck at the GCP loading logo animation.

Dunno what happened, but now it seems this is no longer an issue. Therefore I'm closing this issue.
